<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" parallel="tests" name="Error Validation(failed)">
    <classes>
      <class name="VidhyaPrakashAutomation.Tests.ErrorValidationTest">
        <methods>
          <include name="loginErrorValidation"/>
          <include name="launchApplication"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- VidhyaPrakashAutomation.Tests.ErrorValidationTest -->
    </classes>
  </test> <!-- Error Validation(failed) -->
  <test thread-count="5" parallel="tests" name="Submit Order(failed)">
    <classes>
      <class name="VidhyaPrakashAutomation.Tests.SubmitOrder">
        <methods>
          <include name="launchApplication"/>
          <include name="submitOrder" invocation-numbers="0 1"/>
          <include name="tearDown"/>
          <include name="orderHistory"/>
        </methods>
      </class> <!-- VidhyaPrakashAutomation.Tests.SubmitOrder -->
    </classes>
  </test> <!-- Submit Order(failed) -->
</suite> <!-- Failed suite [Suite] -->
